spring.datasource.url=jdbc:postgresql://localhost:5432/db_ventas_cordillera
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.cloud.discovery.enabled=false
spring.cloud.service-registry.auto-registration.enabled=false
logging.level.org.springframework.security=DEBUG
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
